# Name of workflow
name: Actions CI

# Trigger the workflow on push or pull request
on:
  push:
  pull_request:

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # Если у вас нет скрипта make install, используйте npm install или аналогичное
      # - run: make install

      - run: make lint
      - run: make test

      # Если у вас есть скрипт npm run coverage для генерации отчетов о покрытии, используйте его
      - name: Run Test Coverage
        run: npm run coverage

      # Использование Code Climate Action для отправки отчетов о покрытии кода
      - name: Code Climate Test Reporting
        uses: paambaati/codeclimate-action@v5.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: npm run coverage
          debug: true
